version: '3.8'

services:
  backend:
    
    image: ${DOCKER_USERNAME}/my-backend:latest
    container_name: backend-container
    restart: always
    expose:
      - "5000"
    

  frontend:
    image: ${DOCKER_USERNAME}/my-frontend:latest
    container_name: frontend-container
    restart: always
    ports:
      - "127.0.0.1:5000:5000" 
    depends_on:
      - backend
