version: '3.8'

services:
  backend:
    image: ${{ DOCKER_USERNAME }}/my-backend:latest
    container_name: backend-container
    restart: always
    expose:
      - "5000" # Not mapped to host, only internal
    env_file: .env

  frontend:
    image: ${{ DOCKER_USERNAME }}/my-frontend:latest
    container_name: frontend-container
    restart: always
    expose:
      - "80"   # Not mapped to host, accessed via Nginx
    depends_on:
      - backend

