apiVersion: apps/v1
kind: Deployment
metadata: { name: backend }
spec:
  replicas: 1
  selector: { matchLabels: { app: backend } }
  template:
    metadata: { labels: { app: backend } }
    spec:
      containers:
      - name: backend
        image: 239013465433.dkr.ecr.us-east-2.amazonaws.com/my-backend:latest
        ports: [{ containerPort: 5000 }]
---
apiVersion: v1
kind: Service
metadata: { name: backend } 
spec:
  selector: { app: backend }
  ports: [{ port: 5000, targetPort: 5000 }]
